export const SET_MOVIE_LIST = "SET_MOVIE_LIST"
export const SET_MOVIE_DETAIL = "SET_MOVIE_DETAIL"
export const SET_SHOWTIME_DETAIL = "SET_SHOWTIME_DETAIL"
export const SET_TICKET_TYPE = "SET_TICKET_TYPE"
export const SET_SEAT = "SET_SEAT"
export const SET_COMBO = "SET_COMBO"
export const SEATED = "SEATED"
export const SEAT_BEING_SELECTED = "SEAT_BEING_SELECTED"
export const SEAT_HAS_BEEN_CHOSEN = "SEAT_HAS_BEEN_CHOSEN"
export const SEAT_DIS_CONNECTION = "SEAT_DIS_CONNECTION"
export const SEAT_DIS_CONNECTION_NULL = "SEAT_DIS_CONNECTION_NULL"
export const LIST_OF_SEAT_THE_USER_IS_CURRENTLY_SELECTING = "LIST_OF_SEAT_THE_USER_IS_CURRENTLY_SELECTING"

export const TICKET_BOOKING_SUCCESSFUL = "TICKET_BOOKING_SUCCESSFUL";