<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Cinema.Business.Contracts\Cinema.Business.Contracts.csproj" />
    <ProjectReference Include="..\Cinema.Business.DTO\Cinema.Business.DTO.csproj" />
    <ProjectReference Include="..\..\3-Data\Cinema.Data.Contracts\Cinema.Data.Contracts.csproj" />
    <ProjectReference Include="..\..\4-Foundation\Cinema.Foundation\Cinema.Foundation.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Auth" Version="1.75.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
