/* spellcheck: off */

//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';

export class CinemaServiceAgent { }
export namespace CinemaServiceAgent {
export const CINEMA_BASE_URL = new InjectionToken<string>('CINEMA_BASE_URL');

export interface IHttpService {
    getMovies(search: PagingSearchDTO): Observable<DefaultSearchResultsOfMovieDTO>;
    getNowShowingMovies(search: PagingSearchDTO): Observable<DefaultSearchResultsOfMovieDTO>;
    getComingSoonMovies(search: PagingSearchDTO): Observable<DefaultSearchResultsOfMovieDTO>;
    getMovie(id?: string | undefined): Observable<MovieDetailDTO>;
    createMovie(request: CreateMovieRequest): Observable<MovieDetailDTO>;
    updateMovie(request: UpdateMovieRequest): Observable<MovieDetailDTO>;
    deleteMovie(id?: string | undefined): Observable<void>;
    addComment(request: AddCommentRequest, movieId?: string | undefined): Observable<CommentDTO>;
    rateMovie(request: RateMovieRequest, movieId?: string | undefined): Observable<void>;
    getTheaters(search: PagingSearchDTO): Observable<DefaultSearchResultsOfTheaterDTO>;
    getTheater(id?: string | undefined): Observable<TheaterDTO>;
    getTheatersByMovie(search: PagingSearchDTO): Observable<DefaultSearchResultsOfTheaterDTO>;
    createTheater(request: CreateTheaterRequest): Observable<TheaterDTO>;
    updateTheater(request: UpdateTheaterRequest): Observable<TheaterDTO>;
    deleteTheater(id?: string | undefined): Observable<void>;
    getShowTimes(search: PagingSearchDTO): Observable<DefaultSearchResultsOfShowTimeListDTO>;
}

@Injectable()
export class HttpService implements IHttpService {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(CINEMA_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ?? "localhost:5102";
    }

    getMovies(search: PagingSearchDTO): Observable<DefaultSearchResultsOfMovieDTO> {
        let url_ = this.baseUrl + "/api/Cinema/GetMovies";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(search);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetMovies(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetMovies(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<DefaultSearchResultsOfMovieDTO>;
                }
            } else
                return _observableThrow(response_) as any as Observable<DefaultSearchResultsOfMovieDTO>;
        }));
    }

    protected processGetMovies(response: HttpResponseBase): Observable<DefaultSearchResultsOfMovieDTO> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = DefaultSearchResultsOfMovieDTO.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    getNowShowingMovies(search: PagingSearchDTO): Observable<DefaultSearchResultsOfMovieDTO> {
        let url_ = this.baseUrl + "/api/Cinema/GetNowShowingMovies";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(search);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetNowShowingMovies(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetNowShowingMovies(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<DefaultSearchResultsOfMovieDTO>;
                }
            } else
                return _observableThrow(response_) as any as Observable<DefaultSearchResultsOfMovieDTO>;
        }));
    }

    protected processGetNowShowingMovies(response: HttpResponseBase): Observable<DefaultSearchResultsOfMovieDTO> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = DefaultSearchResultsOfMovieDTO.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    getComingSoonMovies(search: PagingSearchDTO): Observable<DefaultSearchResultsOfMovieDTO> {
        let url_ = this.baseUrl + "/api/Cinema/GetComingSoonMovies";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(search);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetComingSoonMovies(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetComingSoonMovies(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<DefaultSearchResultsOfMovieDTO>;
                }
            } else
                return _observableThrow(response_) as any as Observable<DefaultSearchResultsOfMovieDTO>;
        }));
    }

    protected processGetComingSoonMovies(response: HttpResponseBase): Observable<DefaultSearchResultsOfMovieDTO> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = DefaultSearchResultsOfMovieDTO.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    getMovie(id?: string | undefined): Observable<MovieDetailDTO> {
        let url_ = this.baseUrl + "/api/Cinema/GetMovie?";
        if (id === null)
            throw new Error("The parameter 'id' cannot be null.");
        else if (id !== undefined)
            url_ += "id=" + encodeURIComponent("" + id) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetMovie(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetMovie(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<MovieDetailDTO>;
                }
            } else
                return _observableThrow(response_) as any as Observable<MovieDetailDTO>;
        }));
    }

    protected processGetMovie(response: HttpResponseBase): Observable<MovieDetailDTO> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = MovieDetailDTO.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    createMovie(request: CreateMovieRequest): Observable<MovieDetailDTO> {
        let url_ = this.baseUrl + "/api/Cinema/CreateMovie";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processCreateMovie(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processCreateMovie(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<MovieDetailDTO>;
                }
            } else
                return _observableThrow(response_) as any as Observable<MovieDetailDTO>;
        }));
    }

    protected processCreateMovie(response: HttpResponseBase): Observable<MovieDetailDTO> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = MovieDetailDTO.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    updateMovie(request: UpdateMovieRequest): Observable<MovieDetailDTO> {
        let url_ = this.baseUrl + "/api/Cinema/UpdateMovie";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("put", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processUpdateMovie(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processUpdateMovie(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<MovieDetailDTO>;
                }
            } else
                return _observableThrow(response_) as any as Observable<MovieDetailDTO>;
        }));
    }

    protected processUpdateMovie(response: HttpResponseBase): Observable<MovieDetailDTO> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = MovieDetailDTO.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    deleteMovie(id?: string | undefined): Observable<void> {
        let url_ = this.baseUrl + "/api/Cinema/DeleteMovie?";
        if (id === null)
            throw new Error("The parameter 'id' cannot be null.");
        else if (id !== undefined)
            url_ += "id=" + encodeURIComponent("" + id) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
            })
        };

        return this.http.request("delete", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processDeleteMovie(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processDeleteMovie(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<void>;
                }
            } else
                return _observableThrow(response_) as any as Observable<void>;
        }));
    }

    protected processDeleteMovie(response: HttpResponseBase): Observable<void> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return _observableOf(null as any);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    addComment(request: AddCommentRequest, movieId?: string | undefined): Observable<CommentDTO> {
        let url_ = this.baseUrl + "/api/Cinema/AddComment?";
        if (movieId === null)
            throw new Error("The parameter 'movieId' cannot be null.");
        else if (movieId !== undefined)
            url_ += "movieId=" + encodeURIComponent("" + movieId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processAddComment(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processAddComment(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<CommentDTO>;
                }
            } else
                return _observableThrow(response_) as any as Observable<CommentDTO>;
        }));
    }

    protected processAddComment(response: HttpResponseBase): Observable<CommentDTO> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = CommentDTO.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    rateMovie(request: RateMovieRequest, movieId?: string | undefined): Observable<void> {
        let url_ = this.baseUrl + "/api/Cinema/RateMovie?";
        if (movieId === null)
            throw new Error("The parameter 'movieId' cannot be null.");
        else if (movieId !== undefined)
            url_ += "movieId=" + encodeURIComponent("" + movieId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processRateMovie(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processRateMovie(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<void>;
                }
            } else
                return _observableThrow(response_) as any as Observable<void>;
        }));
    }

    protected processRateMovie(response: HttpResponseBase): Observable<void> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return _observableOf(null as any);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    getTheaters(search: PagingSearchDTO): Observable<DefaultSearchResultsOfTheaterDTO> {
        let url_ = this.baseUrl + "/api/Cinema/GetTheaters";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(search);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetTheaters(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetTheaters(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<DefaultSearchResultsOfTheaterDTO>;
                }
            } else
                return _observableThrow(response_) as any as Observable<DefaultSearchResultsOfTheaterDTO>;
        }));
    }

    protected processGetTheaters(response: HttpResponseBase): Observable<DefaultSearchResultsOfTheaterDTO> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = DefaultSearchResultsOfTheaterDTO.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    getTheater(id?: string | undefined): Observable<TheaterDTO> {
        let url_ = this.baseUrl + "/api/Cinema/GetTheater?";
        if (id === null)
            throw new Error("The parameter 'id' cannot be null.");
        else if (id !== undefined)
            url_ += "id=" + encodeURIComponent("" + id) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetTheater(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetTheater(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<TheaterDTO>;
                }
            } else
                return _observableThrow(response_) as any as Observable<TheaterDTO>;
        }));
    }

    protected processGetTheater(response: HttpResponseBase): Observable<TheaterDTO> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = TheaterDTO.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    getTheatersByMovie(search: PagingSearchDTO): Observable<DefaultSearchResultsOfTheaterDTO> {
        let url_ = this.baseUrl + "/api/Cinema/GetTheatersByMovie";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(search);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetTheatersByMovie(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetTheatersByMovie(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<DefaultSearchResultsOfTheaterDTO>;
                }
            } else
                return _observableThrow(response_) as any as Observable<DefaultSearchResultsOfTheaterDTO>;
        }));
    }

    protected processGetTheatersByMovie(response: HttpResponseBase): Observable<DefaultSearchResultsOfTheaterDTO> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = DefaultSearchResultsOfTheaterDTO.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    createTheater(request: CreateTheaterRequest): Observable<TheaterDTO> {
        let url_ = this.baseUrl + "/api/Cinema/CreateTheater";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processCreateTheater(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processCreateTheater(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<TheaterDTO>;
                }
            } else
                return _observableThrow(response_) as any as Observable<TheaterDTO>;
        }));
    }

    protected processCreateTheater(response: HttpResponseBase): Observable<TheaterDTO> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = TheaterDTO.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    updateTheater(request: UpdateTheaterRequest): Observable<TheaterDTO> {
        let url_ = this.baseUrl + "/api/Cinema/UpdateTheater";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("put", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processUpdateTheater(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processUpdateTheater(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<TheaterDTO>;
                }
            } else
                return _observableThrow(response_) as any as Observable<TheaterDTO>;
        }));
    }

    protected processUpdateTheater(response: HttpResponseBase): Observable<TheaterDTO> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = TheaterDTO.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    deleteTheater(id?: string | undefined): Observable<void> {
        let url_ = this.baseUrl + "/api/Cinema/DeleteTheater?";
        if (id === null)
            throw new Error("The parameter 'id' cannot be null.");
        else if (id !== undefined)
            url_ += "id=" + encodeURIComponent("" + id) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
            })
        };

        return this.http.request("delete", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processDeleteTheater(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processDeleteTheater(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<void>;
                }
            } else
                return _observableThrow(response_) as any as Observable<void>;
        }));
    }

    protected processDeleteTheater(response: HttpResponseBase): Observable<void> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return _observableOf(null as any);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    getShowTimes(search: PagingSearchDTO): Observable<DefaultSearchResultsOfShowTimeListDTO> {
        let url_ = this.baseUrl + "/api/Cinema/GetShowTimes";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(search);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetShowTimes(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetShowTimes(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<DefaultSearchResultsOfShowTimeListDTO>;
                }
            } else
                return _observableThrow(response_) as any as Observable<DefaultSearchResultsOfShowTimeListDTO>;
        }));
    }

    protected processGetShowTimes(response: HttpResponseBase): Observable<DefaultSearchResultsOfShowTimeListDTO> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = DefaultSearchResultsOfShowTimeListDTO.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

export abstract class BaseSearchResultsOfMovieDTO implements IBaseSearchResultsOfMovieDTO {
    results?: MovieDTO[];
    totalCount?: number;
    countPerPage?: number;
    page?: number;

    constructor(data?: IBaseSearchResultsOfMovieDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["results"])) {
                this.results = [] as any;
                for (let item of _data["results"])
                    this.results!.push(MovieDTO.fromJS(item));
            }
            this.totalCount = _data["totalCount"];
            this.countPerPage = _data["countPerPage"];
            this.page = _data["page"];
        }
    }

    static fromJS(data: any): BaseSearchResultsOfMovieDTO {
        data = typeof data === 'object' ? data : {};
        throw new Error("The abstract class 'BaseSearchResultsOfMovieDTO' cannot be instantiated.");
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.results)) {
            data["results"] = [];
            for (let item of this.results)
                data["results"].push(item.toJSON());
        }
        data["totalCount"] = this.totalCount;
        data["countPerPage"] = this.countPerPage;
        data["page"] = this.page;
        return data;
    }
}

export interface IBaseSearchResultsOfMovieDTO {
    results?: MovieDTO[];
    totalCount?: number;
    countPerPage?: number;
    page?: number;
}

export class DefaultSearchResultsOfMovieDTO extends BaseSearchResultsOfMovieDTO implements IDefaultSearchResultsOfMovieDTO {

    constructor(data?: IDefaultSearchResultsOfMovieDTO) {
        super(data);
    }

    override init(_data?: any) {
        super.init(_data);
    }

    static override fromJS(data: any): DefaultSearchResultsOfMovieDTO {
        data = typeof data === 'object' ? data : {};
        let result = new DefaultSearchResultsOfMovieDTO();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        super.toJSON(data);
        return data;
    }
}

export interface IDefaultSearchResultsOfMovieDTO extends IBaseSearchResultsOfMovieDTO {
}

export class MovieDTO implements IMovieDTO {
    id?: string;
    title?: string;
    description?: string;
    duration?: number;
    releaseDate?: Date;
    endDate?: Date | undefined;
    posterUrl?: string | undefined;
    trailerUrl?: string | undefined;
    director?: string | undefined;
    cast?: string | undefined;
    language?: string | undefined;
    ageRestrictionCode?: string;
    genres?: string[];
    averageRating?: number;
    ratingCount?: number;
    isActive?: boolean;
    isNowShowing?: boolean;
    isComingSoon?: boolean;

    constructor(data?: IMovieDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.title = _data["title"];
            this.description = _data["description"];
            this.duration = _data["duration"];
            this.releaseDate = _data["releaseDate"] ? new Date(_data["releaseDate"].toString()) : <any>undefined;
            this.endDate = _data["endDate"] ? new Date(_data["endDate"].toString()) : <any>undefined;
            this.posterUrl = _data["posterUrl"];
            this.trailerUrl = _data["trailerUrl"];
            this.director = _data["director"];
            this.cast = _data["cast"];
            this.language = _data["language"];
            this.ageRestrictionCode = _data["ageRestrictionCode"];
            if (Array.isArray(_data["genres"])) {
                this.genres = [] as any;
                for (let item of _data["genres"])
                    this.genres!.push(item);
            }
            this.averageRating = _data["averageRating"];
            this.ratingCount = _data["ratingCount"];
            this.isActive = _data["isActive"];
            this.isNowShowing = _data["isNowShowing"];
            this.isComingSoon = _data["isComingSoon"];
        }
    }

    static fromJS(data: any): MovieDTO {
        data = typeof data === 'object' ? data : {};
        let result = new MovieDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["title"] = this.title;
        data["description"] = this.description;
        data["duration"] = this.duration;
        data["releaseDate"] = this.releaseDate ? formatDate(this.releaseDate) : <any>undefined;
        data["endDate"] = this.endDate ? formatDate(this.endDate) : <any>undefined;
        data["posterUrl"] = this.posterUrl;
        data["trailerUrl"] = this.trailerUrl;
        data["director"] = this.director;
        data["cast"] = this.cast;
        data["language"] = this.language;
        data["ageRestrictionCode"] = this.ageRestrictionCode;
        if (Array.isArray(this.genres)) {
            data["genres"] = [];
            for (let item of this.genres)
                data["genres"].push(item);
        }
        data["averageRating"] = this.averageRating;
        data["ratingCount"] = this.ratingCount;
        data["isActive"] = this.isActive;
        data["isNowShowing"] = this.isNowShowing;
        data["isComingSoon"] = this.isComingSoon;
        return data;
    }
}

export interface IMovieDTO {
    id?: string;
    title?: string;
    description?: string;
    duration?: number;
    releaseDate?: Date;
    endDate?: Date | undefined;
    posterUrl?: string | undefined;
    trailerUrl?: string | undefined;
    director?: string | undefined;
    cast?: string | undefined;
    language?: string | undefined;
    ageRestrictionCode?: string;
    genres?: string[];
    averageRating?: number;
    ratingCount?: number;
    isActive?: boolean;
    isNowShowing?: boolean;
    isComingSoon?: boolean;
}

export class PagingSearchDTO implements IPagingSearchDTO {
    pageIndex?: number;
    pageSize?: number;
    filters?: { [key: string]: string; } | undefined;
    sort?: SortDTO | undefined;

    constructor(data?: IPagingSearchDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.pageIndex = _data["pageIndex"];
            this.pageSize = _data["pageSize"];
            if (_data["filters"]) {
                this.filters = {} as any;
                for (let key in _data["filters"]) {
                    if (_data["filters"].hasOwnProperty(key))
                        (<any>this.filters)![key] = _data["filters"][key];
                }
            }
            this.sort = _data["sort"] ? SortDTO.fromJS(_data["sort"]) : <any>undefined;
        }
    }

    static fromJS(data: any): PagingSearchDTO {
        data = typeof data === 'object' ? data : {};
        let result = new PagingSearchDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["pageIndex"] = this.pageIndex;
        data["pageSize"] = this.pageSize;
        if (this.filters) {
            data["filters"] = {};
            for (let key in this.filters) {
                if (this.filters.hasOwnProperty(key))
                    (<any>data["filters"])[key] = (<any>this.filters)[key];
            }
        }
        data["sort"] = this.sort ? this.sort.toJSON() : <any>undefined;
        return data;
    }
}

export interface IPagingSearchDTO {
    pageIndex?: number;
    pageSize?: number;
    filters?: { [key: string]: string; } | undefined;
    sort?: SortDTO | undefined;
}

export class SortDTO implements ISortDTO {
    field?: string;
    ascending?: boolean;

    constructor(data?: ISortDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.field = _data["field"];
            this.ascending = _data["ascending"];
        }
    }

    static fromJS(data: any): SortDTO {
        data = typeof data === 'object' ? data : {};
        let result = new SortDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["field"] = this.field;
        data["ascending"] = this.ascending;
        return data;
    }
}

export interface ISortDTO {
    field?: string;
    ascending?: boolean;
}

export class MovieDetailDTO extends MovieDTO implements IMovieDetailDTO {
    ageRestrictionDescription?: string;
    ageRestrictionMinAge?: number;
    showTimes?: ShowTimeSummaryDTO[];
    recentComments?: CommentDTO[];

    constructor(data?: IMovieDetailDTO) {
        super(data);
    }

    override init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.ageRestrictionDescription = _data["ageRestrictionDescription"];
            this.ageRestrictionMinAge = _data["ageRestrictionMinAge"];
            if (Array.isArray(_data["showTimes"])) {
                this.showTimes = [] as any;
                for (let item of _data["showTimes"])
                    this.showTimes!.push(ShowTimeSummaryDTO.fromJS(item));
            }
            if (Array.isArray(_data["recentComments"])) {
                this.recentComments = [] as any;
                for (let item of _data["recentComments"])
                    this.recentComments!.push(CommentDTO.fromJS(item));
            }
        }
    }

    static override fromJS(data: any): MovieDetailDTO {
        data = typeof data === 'object' ? data : {};
        let result = new MovieDetailDTO();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["ageRestrictionDescription"] = this.ageRestrictionDescription;
        data["ageRestrictionMinAge"] = this.ageRestrictionMinAge;
        if (Array.isArray(this.showTimes)) {
            data["showTimes"] = [];
            for (let item of this.showTimes)
                data["showTimes"].push(item.toJSON());
        }
        if (Array.isArray(this.recentComments)) {
            data["recentComments"] = [];
            for (let item of this.recentComments)
                data["recentComments"].push(item.toJSON());
        }
        super.toJSON(data);
        return data;
    }
}

export interface IMovieDetailDTO extends IMovieDTO {
    ageRestrictionDescription?: string;
    ageRestrictionMinAge?: number;
    showTimes?: ShowTimeSummaryDTO[];
    recentComments?: CommentDTO[];
}

export class ShowTimeSummaryDTO implements IShowTimeSummaryDTO {
    id?: string;
    startTime?: Date;
    endTime?: Date;
    projectionForm?: ProjectionForm;
    theaterName?: string;
    roomName?: string;
    roomId?: string;
    availableSeats?: number;

    constructor(data?: IShowTimeSummaryDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.startTime = _data["startTime"] ? new Date(_data["startTime"].toString()) : <any>undefined;
            this.endTime = _data["endTime"] ? new Date(_data["endTime"].toString()) : <any>undefined;
            this.projectionForm = _data["projectionForm"];
            this.theaterName = _data["theaterName"];
            this.roomName = _data["roomName"];
            this.roomId = _data["roomId"];
            this.availableSeats = _data["availableSeats"];
        }
    }

    static fromJS(data: any): ShowTimeSummaryDTO {
        data = typeof data === 'object' ? data : {};
        let result = new ShowTimeSummaryDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["startTime"] = this.startTime ? this.startTime.toISOString() : <any>undefined;
        data["endTime"] = this.endTime ? this.endTime.toISOString() : <any>undefined;
        data["projectionForm"] = this.projectionForm;
        data["theaterName"] = this.theaterName;
        data["roomName"] = this.roomName;
        data["roomId"] = this.roomId;
        data["availableSeats"] = this.availableSeats;
        return data;
    }
}

export interface IShowTimeSummaryDTO {
    id?: string;
    startTime?: Date;
    endTime?: Date;
    projectionForm?: ProjectionForm;
    theaterName?: string;
    roomName?: string;
    roomId?: string;
    availableSeats?: number;
}

export enum ProjectionForm {
    TwoD = 1,
    ThreeD = 2,
    IMAX = 3,
}

export class CommentDTO implements ICommentDTO {
    id?: string;
    content?: string;
    userName?: string;
    userAvatar?: string | undefined;
    parentId?: string | undefined;
    creationTime?: Date;
    replies?: CommentDTO[];

    constructor(data?: ICommentDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.content = _data["content"];
            this.userName = _data["userName"];
            this.userAvatar = _data["userAvatar"];
            this.parentId = _data["parentId"];
            this.creationTime = _data["creationTime"] ? new Date(_data["creationTime"].toString()) : <any>undefined;
            if (Array.isArray(_data["replies"])) {
                this.replies = [] as any;
                for (let item of _data["replies"])
                    this.replies!.push(CommentDTO.fromJS(item));
            }
        }
    }

    static fromJS(data: any): CommentDTO {
        data = typeof data === 'object' ? data : {};
        let result = new CommentDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["content"] = this.content;
        data["userName"] = this.userName;
        data["userAvatar"] = this.userAvatar;
        data["parentId"] = this.parentId;
        data["creationTime"] = this.creationTime ? this.creationTime.toISOString() : <any>undefined;
        if (Array.isArray(this.replies)) {
            data["replies"] = [];
            for (let item of this.replies)
                data["replies"].push(item.toJSON());
        }
        return data;
    }
}

export interface ICommentDTO {
    id?: string;
    content?: string;
    userName?: string;
    userAvatar?: string | undefined;
    parentId?: string | undefined;
    creationTime?: Date;
    replies?: CommentDTO[];
}

export class CreateMovieRequest implements ICreateMovieRequest {
    title?: string;
    description?: string;
    duration?: number;
    releaseDate?: Date;
    endDate?: Date | undefined;
    posterUrl?: string | undefined;
    trailerUrl?: string | undefined;
    director?: string | undefined;
    cast?: string | undefined;
    language?: string | undefined;
    subtitle?: string | undefined;
    ageRestrictionId?: string;
    movieTypeIds?: string[];

    constructor(data?: ICreateMovieRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.title = _data["title"];
            this.description = _data["description"];
            this.duration = _data["duration"];
            this.releaseDate = _data["releaseDate"] ? new Date(_data["releaseDate"].toString()) : <any>undefined;
            this.endDate = _data["endDate"] ? new Date(_data["endDate"].toString()) : <any>undefined;
            this.posterUrl = _data["posterUrl"];
            this.trailerUrl = _data["trailerUrl"];
            this.director = _data["director"];
            this.cast = _data["cast"];
            this.language = _data["language"];
            this.subtitle = _data["subtitle"];
            this.ageRestrictionId = _data["ageRestrictionId"];
            if (Array.isArray(_data["movieTypeIds"])) {
                this.movieTypeIds = [] as any;
                for (let item of _data["movieTypeIds"])
                    this.movieTypeIds!.push(item);
            }
        }
    }

    static fromJS(data: any): CreateMovieRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CreateMovieRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["title"] = this.title;
        data["description"] = this.description;
        data["duration"] = this.duration;
        data["releaseDate"] = this.releaseDate ? formatDate(this.releaseDate) : <any>undefined;
        data["endDate"] = this.endDate ? formatDate(this.endDate) : <any>undefined;
        data["posterUrl"] = this.posterUrl;
        data["trailerUrl"] = this.trailerUrl;
        data["director"] = this.director;
        data["cast"] = this.cast;
        data["language"] = this.language;
        data["subtitle"] = this.subtitle;
        data["ageRestrictionId"] = this.ageRestrictionId;
        if (Array.isArray(this.movieTypeIds)) {
            data["movieTypeIds"] = [];
            for (let item of this.movieTypeIds)
                data["movieTypeIds"].push(item);
        }
        return data;
    }
}

export interface ICreateMovieRequest {
    title?: string;
    description?: string;
    duration?: number;
    releaseDate?: Date;
    endDate?: Date | undefined;
    posterUrl?: string | undefined;
    trailerUrl?: string | undefined;
    director?: string | undefined;
    cast?: string | undefined;
    language?: string | undefined;
    subtitle?: string | undefined;
    ageRestrictionId?: string;
    movieTypeIds?: string[];
}

export class UpdateMovieRequest implements IUpdateMovieRequest {
    id?: string;
    title?: string;
    description?: string;
    duration?: number;
    releaseDate?: Date;
    endDate?: Date | undefined;
    posterUrl?: string | undefined;
    trailerUrl?: string | undefined;
    director?: string | undefined;
    cast?: string | undefined;
    language?: string | undefined;
    subtitle?: string | undefined;
    ageRestrictionId?: string;
    movieTypeIds?: string[];

    constructor(data?: IUpdateMovieRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.title = _data["title"];
            this.description = _data["description"];
            this.duration = _data["duration"];
            this.releaseDate = _data["releaseDate"] ? new Date(_data["releaseDate"].toString()) : <any>undefined;
            this.endDate = _data["endDate"] ? new Date(_data["endDate"].toString()) : <any>undefined;
            this.posterUrl = _data["posterUrl"];
            this.trailerUrl = _data["trailerUrl"];
            this.director = _data["director"];
            this.cast = _data["cast"];
            this.language = _data["language"];
            this.subtitle = _data["subtitle"];
            this.ageRestrictionId = _data["ageRestrictionId"];
            if (Array.isArray(_data["movieTypeIds"])) {
                this.movieTypeIds = [] as any;
                for (let item of _data["movieTypeIds"])
                    this.movieTypeIds!.push(item);
            }
        }
    }

    static fromJS(data: any): UpdateMovieRequest {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateMovieRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["title"] = this.title;
        data["description"] = this.description;
        data["duration"] = this.duration;
        data["releaseDate"] = this.releaseDate ? formatDate(this.releaseDate) : <any>undefined;
        data["endDate"] = this.endDate ? formatDate(this.endDate) : <any>undefined;
        data["posterUrl"] = this.posterUrl;
        data["trailerUrl"] = this.trailerUrl;
        data["director"] = this.director;
        data["cast"] = this.cast;
        data["language"] = this.language;
        data["subtitle"] = this.subtitle;
        data["ageRestrictionId"] = this.ageRestrictionId;
        if (Array.isArray(this.movieTypeIds)) {
            data["movieTypeIds"] = [];
            for (let item of this.movieTypeIds)
                data["movieTypeIds"].push(item);
        }
        return data;
    }
}

export interface IUpdateMovieRequest {
    id?: string;
    title?: string;
    description?: string;
    duration?: number;
    releaseDate?: Date;
    endDate?: Date | undefined;
    posterUrl?: string | undefined;
    trailerUrl?: string | undefined;
    director?: string | undefined;
    cast?: string | undefined;
    language?: string | undefined;
    subtitle?: string | undefined;
    ageRestrictionId?: string;
    movieTypeIds?: string[];
}

export class AddCommentRequest implements IAddCommentRequest {
    content?: string;
    parentId?: string | undefined;

    constructor(data?: IAddCommentRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.content = _data["content"];
            this.parentId = _data["parentId"];
        }
    }

    static fromJS(data: any): AddCommentRequest {
        data = typeof data === 'object' ? data : {};
        let result = new AddCommentRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["content"] = this.content;
        data["parentId"] = this.parentId;
        return data;
    }
}

export interface IAddCommentRequest {
    content?: string;
    parentId?: string | undefined;
}

export class RateMovieRequest implements IRateMovieRequest {
    score?: number;
    review?: string | undefined;

    constructor(data?: IRateMovieRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.score = _data["score"];
            this.review = _data["review"];
        }
    }

    static fromJS(data: any): RateMovieRequest {
        data = typeof data === 'object' ? data : {};
        let result = new RateMovieRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["score"] = this.score;
        data["review"] = this.review;
        return data;
    }
}

export interface IRateMovieRequest {
    score?: number;
    review?: string | undefined;
}

export abstract class BaseSearchResultsOfTheaterDTO implements IBaseSearchResultsOfTheaterDTO {
    results?: TheaterDTO[];
    totalCount?: number;
    countPerPage?: number;
    page?: number;

    constructor(data?: IBaseSearchResultsOfTheaterDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["results"])) {
                this.results = [] as any;
                for (let item of _data["results"])
                    this.results!.push(TheaterDTO.fromJS(item));
            }
            this.totalCount = _data["totalCount"];
            this.countPerPage = _data["countPerPage"];
            this.page = _data["page"];
        }
    }

    static fromJS(data: any): BaseSearchResultsOfTheaterDTO {
        data = typeof data === 'object' ? data : {};
        throw new Error("The abstract class 'BaseSearchResultsOfTheaterDTO' cannot be instantiated.");
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.results)) {
            data["results"] = [];
            for (let item of this.results)
                data["results"].push(item.toJSON());
        }
        data["totalCount"] = this.totalCount;
        data["countPerPage"] = this.countPerPage;
        data["page"] = this.page;
        return data;
    }
}

export interface IBaseSearchResultsOfTheaterDTO {
    results?: TheaterDTO[];
    totalCount?: number;
    countPerPage?: number;
    page?: number;
}

export class DefaultSearchResultsOfTheaterDTO extends BaseSearchResultsOfTheaterDTO implements IDefaultSearchResultsOfTheaterDTO {

    constructor(data?: IDefaultSearchResultsOfTheaterDTO) {
        super(data);
    }

    override init(_data?: any) {
        super.init(_data);
    }

    static override fromJS(data: any): DefaultSearchResultsOfTheaterDTO {
        data = typeof data === 'object' ? data : {};
        let result = new DefaultSearchResultsOfTheaterDTO();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        super.toJSON(data);
        return data;
    }
}

export interface IDefaultSearchResultsOfTheaterDTO extends IBaseSearchResultsOfTheaterDTO {
}

export class TheaterDTO implements ITheaterDTO {
    id?: string;
    name?: string;
    address?: string;
    city?: string;
    phone?: string | undefined;
    imageUrl?: string | undefined;
    roomCount?: number;
    isActive?: boolean;

    constructor(data?: ITheaterDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
            this.address = _data["address"];
            this.city = _data["city"];
            this.phone = _data["phone"];
            this.imageUrl = _data["imageUrl"];
            this.roomCount = _data["roomCount"];
            this.isActive = _data["isActive"];
        }
    }

    static fromJS(data: any): TheaterDTO {
        data = typeof data === 'object' ? data : {};
        let result = new TheaterDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        data["address"] = this.address;
        data["city"] = this.city;
        data["phone"] = this.phone;
        data["imageUrl"] = this.imageUrl;
        data["roomCount"] = this.roomCount;
        data["isActive"] = this.isActive;
        return data;
    }
}

export interface ITheaterDTO {
    id?: string;
    name?: string;
    address?: string;
    city?: string;
    phone?: string | undefined;
    imageUrl?: string | undefined;
    roomCount?: number;
    isActive?: boolean;
}

export class CreateTheaterRequest implements ICreateTheaterRequest {
    name?: string;
    address?: string;
    city?: string;
    phone?: string | undefined;
    email?: string | undefined;
    imageUrl?: string | undefined;

    constructor(data?: ICreateTheaterRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
            this.address = _data["address"];
            this.city = _data["city"];
            this.phone = _data["phone"];
            this.email = _data["email"];
            this.imageUrl = _data["imageUrl"];
        }
    }

    static fromJS(data: any): CreateTheaterRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CreateTheaterRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["address"] = this.address;
        data["city"] = this.city;
        data["phone"] = this.phone;
        data["email"] = this.email;
        data["imageUrl"] = this.imageUrl;
        return data;
    }
}

export interface ICreateTheaterRequest {
    name?: string;
    address?: string;
    city?: string;
    phone?: string | undefined;
    email?: string | undefined;
    imageUrl?: string | undefined;
}

export class UpdateTheaterRequest implements IUpdateTheaterRequest {
    id?: string;
    name?: string;
    address?: string;
    city?: string;
    phone?: string | undefined;
    email?: string | undefined;
    imageUrl?: string | undefined;

    constructor(data?: IUpdateTheaterRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
            this.address = _data["address"];
            this.city = _data["city"];
            this.phone = _data["phone"];
            this.email = _data["email"];
            this.imageUrl = _data["imageUrl"];
        }
    }

    static fromJS(data: any): UpdateTheaterRequest {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateTheaterRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        data["address"] = this.address;
        data["city"] = this.city;
        data["phone"] = this.phone;
        data["email"] = this.email;
        data["imageUrl"] = this.imageUrl;
        return data;
    }
}

export interface IUpdateTheaterRequest {
    id?: string;
    name?: string;
    address?: string;
    city?: string;
    phone?: string | undefined;
    email?: string | undefined;
    imageUrl?: string | undefined;
}

export abstract class BaseSearchResultsOfShowTimeListDTO implements IBaseSearchResultsOfShowTimeListDTO {
    results?: ShowTimeListDTO[];
    totalCount?: number;
    countPerPage?: number;
    page?: number;

    constructor(data?: IBaseSearchResultsOfShowTimeListDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["results"])) {
                this.results = [] as any;
                for (let item of _data["results"])
                    this.results!.push(ShowTimeListDTO.fromJS(item));
            }
            this.totalCount = _data["totalCount"];
            this.countPerPage = _data["countPerPage"];
            this.page = _data["page"];
        }
    }

    static fromJS(data: any): BaseSearchResultsOfShowTimeListDTO {
        data = typeof data === 'object' ? data : {};
        throw new Error("The abstract class 'BaseSearchResultsOfShowTimeListDTO' cannot be instantiated.");
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.results)) {
            data["results"] = [];
            for (let item of this.results)
                data["results"].push(item.toJSON());
        }
        data["totalCount"] = this.totalCount;
        data["countPerPage"] = this.countPerPage;
        data["page"] = this.page;
        return data;
    }
}

export interface IBaseSearchResultsOfShowTimeListDTO {
    results?: ShowTimeListDTO[];
    totalCount?: number;
    countPerPage?: number;
    page?: number;
}

export class DefaultSearchResultsOfShowTimeListDTO extends BaseSearchResultsOfShowTimeListDTO implements IDefaultSearchResultsOfShowTimeListDTO {

    constructor(data?: IDefaultSearchResultsOfShowTimeListDTO) {
        super(data);
    }

    override init(_data?: any) {
        super.init(_data);
    }

    static override fromJS(data: any): DefaultSearchResultsOfShowTimeListDTO {
        data = typeof data === 'object' ? data : {};
        let result = new DefaultSearchResultsOfShowTimeListDTO();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        super.toJSON(data);
        return data;
    }
}

export interface IDefaultSearchResultsOfShowTimeListDTO extends IBaseSearchResultsOfShowTimeListDTO {
}

export class ShowTimeListDTO implements IShowTimeListDTO {
    id?: string;
    startTime?: Date;
    endTime?: Date;
    projectionForm?: ProjectionForm;
    showTimeType?: ShowTimeType;
    rooms?: ShowTimeRoomDTO[];

    constructor(data?: IShowTimeListDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.startTime = _data["startTime"] ? new Date(_data["startTime"].toString()) : <any>undefined;
            this.endTime = _data["endTime"] ? new Date(_data["endTime"].toString()) : <any>undefined;
            this.projectionForm = _data["projectionForm"];
            this.showTimeType = _data["showTimeType"];
            if (Array.isArray(_data["rooms"])) {
                this.rooms = [] as any;
                for (let item of _data["rooms"])
                    this.rooms!.push(ShowTimeRoomDTO.fromJS(item));
            }
        }
    }

    static fromJS(data: any): ShowTimeListDTO {
        data = typeof data === 'object' ? data : {};
        let result = new ShowTimeListDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["startTime"] = this.startTime ? this.startTime.toISOString() : <any>undefined;
        data["endTime"] = this.endTime ? this.endTime.toISOString() : <any>undefined;
        data["projectionForm"] = this.projectionForm;
        data["showTimeType"] = this.showTimeType;
        if (Array.isArray(this.rooms)) {
            data["rooms"] = [];
            for (let item of this.rooms)
                data["rooms"].push(item.toJSON());
        }
        return data;
    }
}

export interface IShowTimeListDTO {
    id?: string;
    startTime?: Date;
    endTime?: Date;
    projectionForm?: ProjectionForm;
    showTimeType?: ShowTimeType;
    rooms?: ShowTimeRoomDTO[];
}

export enum ShowTimeType {
    Normal = 0,
    Premiere = 1,
    Special = 2,
}

export class ShowTimeRoomDTO implements IShowTimeRoomDTO {
    roomId?: string;
    roomName?: string | undefined;
    theaterName?: string | undefined;
    basePrice?: number;

    constructor(data?: IShowTimeRoomDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.roomId = _data["roomId"];
            this.roomName = _data["roomName"];
            this.theaterName = _data["theaterName"];
            this.basePrice = _data["basePrice"];
        }
    }

    static fromJS(data: any): ShowTimeRoomDTO {
        data = typeof data === 'object' ? data : {};
        let result = new ShowTimeRoomDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["roomId"] = this.roomId;
        data["roomName"] = this.roomName;
        data["theaterName"] = this.theaterName;
        data["basePrice"] = this.basePrice;
        return data;
    }
}

export interface IShowTimeRoomDTO {
    roomId?: string;
    roomName?: string | undefined;
    theaterName?: string | undefined;
    basePrice?: number;
}

function formatDate(d: Date) {
    return d.getFullYear() + '-' + 
        (d.getMonth() < 9 ? ('0' + (d.getMonth()+1)) : (d.getMonth()+1)) + '-' +
        (d.getDate() < 10 ? ('0' + d.getDate()) : d.getDate());
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): Observable<any> {
    return _observableThrow(new ApiException(message, status, response, headers, result));
}

function blobToText(blob: any): Observable<string> {
    return new Observable<string>((observer: any) => {
        if (!blob) {
            observer.next("");
            observer.complete();
        } else {
            let reader = new FileReader();
            reader.onload = event => {
                observer.next((event.target as any).result);
                observer.complete();
            };
            reader.readAsText(blob);
        }
    });
}

}