/**
 * Maps the API's fixed English messages to keys under `apiErrors` in the translation files.
 *
 * Managers throw plain English text and ExceptionMiddleware relays it as `{ error }`, so a Vietnamese
 * user would otherwise read English. A fixed message is listed as `exact`; one with interpolated values
 * is a `pattern` whose named groups become the interpolation params of the translation. Order matters
 * for patterns only (first match wins). A message with no rule is shown as the server sent it.
 */
export interface ApiErrorRule {
  key: string;
  exact?: string;
  pattern?: RegExp;
}

export const API_ERROR_RULES: readonly ApiErrorRule[] = [
  { key: 'unexpected', exact: 'An unexpected error occurred.' },
  { key: 'unexpectedServer', exact: 'An unexpected server error occurred.' },
  { key: 'noFileUploaded', exact: 'No file uploaded.' },
  { key: 'fileTooLarge', exact: 'File exceeds the 5 MB limit.' },
  { key: 'imageOnly', exact: 'Only image files (jpg, png, webp, gif) are allowed.' },
  { key: 'paymentConfirmFailed', exact: 'Failed to confirm payment.' },
  { key: 'bookingCancelFailed', exact: 'Cannot cancel this booking.' },
  { key: 'paymentStartFailed', exact: 'Cannot start payment for this invoice.' },
  { key: 'callbackRejected', exact: 'Callback rejected.' },
  { key: 'bookingRefundFailed', exact: 'Cannot refund this booking.' },
  { key: 'invalidEnumDescription', pattern: /^'(?<description>.+?)' is not a valid description for (?<type>.+?)\.$/ },
  { key: 'notFoundAgeRestriction', pattern: /^AgeRestriction (?<id>.+?) not found\.$/ },
  { key: 'notFoundDiscount', pattern: /^Discount (?<id>.+?) not found\.$/ },
  { key: 'notFoundDiscountType', pattern: /^DiscountType (?<id>.+?) not found\.$/ },
  { key: 'notFoundFoodAndDrink', pattern: /^FoodAndDrink (?<id>.+?) not found\.$/ },
  { key: 'notFoundHoliday', pattern: /^Holiday (?<id>.+?) not found\.$/ },
  { key: 'notFoundMemberShip', pattern: /^MemberShip (?<id>.+?) not found\.$/ },
  { key: 'notFoundMovie', pattern: /^Movie (?<id>.+?) not found\.$/ },
  { key: 'notFoundMovieType', pattern: /^MovieType (?<id>.+?) not found\.$/ },
  { key: 'notFoundNews', pattern: /^News (?<id>.+?) not found\.$/ },
  { key: 'notFoundPatronCategory', pattern: /^PatronCategory (?<id>.+?) not found\.$/ },
  { key: 'notFoundRoom', pattern: /^Room (?<id>.+?) not found\.$/ },
  { key: 'notFoundRoomType', pattern: /^RoomType (?<id>.+?) not found\.$/ },
  { key: 'notFoundSeatType', pattern: /^SeatType (?<id>.+?) not found\.$/ },
  { key: 'notFoundShowTime', pattern: /^ShowTime (?<id>.+?) not found\.$/ },
  { key: 'notFoundTicketPrice', pattern: /^TicketPrice (?<id>.+?) not found\.$/ },
  { key: 'notFoundTimeSlot', pattern: /^TimeSlot (?<id>.+?) not found\.$/ },
  { key: 'notFoundUserType', pattern: /^UserType (?<id>.+?) not found\.$/ },
  { key: 'notFoundTheater', pattern: /^Theater (?<id>.+?) not found\.$/ },
  { key: 'notFoundStoragePlan', pattern: /^StoragePlan (?<id>.+?) not found\.$/ },
  { key: 'notFoundInvoice', pattern: /^Invoice (?<id>.+?) not found\.$/ },
  { key: 'seatNotFound', pattern: /^Seat (?<id>.+?) not found\.$/ },
  { key: 'foodItemNotFound', pattern: /^Food item (?<id>.+?) not found\.$/ },
  { key: 'invalidCredentials', exact: 'Invalid credentials.' },
  { key: 'accountLocked', pattern: /^Account locked due to too many failed attempts\. Try again in (?<minutes>.+?) minute\(s\)\.$/ },
  { key: 'verifyEmailFirst', exact: 'Please verify your email address before signing in.' },
  { key: 'emailInUse', exact: 'Email already in use.' },
  { key: 'phoneInUse', exact: 'Phone already in use.' },
  { key: 'customerTypeMissing', exact: 'Customer user type not found.' },
  { key: 'invalidVerificationToken', exact: 'Invalid or expired verification token.' },
  { key: 'invalidCode', exact: 'Invalid or expired code.' },
  { key: 'userNotFound', exact: 'User not found.' },
  { key: 'invalidGoogleToken', exact: 'Invalid Google token.' },
  { key: 'googleEmailUnverified', exact: 'Google account email is not verified.' },
  { key: 'invalidFacebookToken', exact: 'Invalid Facebook token.' },
  { key: 'wrongCurrentPassword', exact: 'Current password is incorrect.' },
  { key: 'invalidResetToken', exact: 'Invalid or expired reset token.' },
  { key: 'userTypeNotFound', exact: 'User type not found.' },
  { key: 'theaterRequiredForRole', pattern: /^A theater is required for the (?<role>.+?) role\.$/ },
  { key: 'theaterNotFound', exact: 'Theater not found.' },
  { key: 'theaterAssignmentRole', pattern: /^Theater assignments only apply to the (?<role>.+?) role\.$/ },
  { key: 'facebookNotConfigured', exact: 'Facebook login is not configured (Facebook:AppId is missing).' },
  { key: 'googleNotConfigured', exact: 'Google login is not configured (Google:ClientId is missing).' },
  { key: 'notAllowedInvoice', exact: 'You are not allowed to access this invoice.' },
  { key: 'seatsJustBooked', exact: 'One or more selected seats were just booked by someone else.' },
  { key: 'showTimeRoomRequired', exact: 'A showtime and room are required to sell seats.' },
  { key: 'invoiceNotExchangeable', exact: 'This invoice can no longer be exchanged.' },
  { key: 'priceOverrideNeedsApproval', exact: 'Manager approval is required for a price override.' },
  { key: 'openDrawerForCash', exact: 'Open a cash drawer before taking cash.' },
  { key: 'openDrawerForCashBack', exact: 'Open a cash drawer before paying cash back.' },
  { key: 'drawerShortForDifference', exact: 'The drawer does not hold enough cash to pay the difference back.' },
  { key: 'showTimeRoomMissing', exact: 'ShowTime/Room combination not found.' },
  { key: 'roomNotOpenForBooking', exact: 'This room is not open for booking.' },
  { key: 'showTimeOtherTheater', exact: 'This showtime does not belong to your theater.' },
  { key: 'showTimeNotOpenForSale', exact: 'This showtime is not open for sale.' },
  { key: 'doubleSeatPartner', exact: 'A double seat must be booked together with its partner.' },
  { key: 'seatAlreadyBooked', pattern: /^Seat (?<seat>.+?) is already booked\.$/ },
  { key: 'seatHeldByOther', pattern: /^Seat (?<seat>.+?) is being held by another user\.$/ },
  { key: 'seatNotInRoom', pattern: /^Seat (?<seat>.+?) does not belong to this room\.$/ },
  { key: 'seatBlocked', pattern: /^Seat (?<seat>.+?) is blocked and cannot be booked\.$/ },
  { key: 'patronRequired', exact: 'A patron category is required for every seat.' },
  { key: 'patronInvalid', exact: 'Selected patron category is invalid or unavailable.' },
  { key: 'seatNotForPatron', pattern: /^Seat (?<seat>.+?) is not available for the selected patron category\.$/ },
  { key: 'giftCardInvalid', exact: 'Invalid or expired gift card.' },
  { key: 'priceOverrideRange', pattern: /^The price override for (?<what>.+?) must be between 0 and its list price\.$/ },
  { key: 'itemNoLongerAvailable', pattern: /^'(?<name>.+?)' is no longer available\.$/ },
  { key: 'itemOutOfStock', pattern: /^'(?<name>.+?)' is out of stock or has insufficient quantity\.$/ },
  { key: 'itemNotAtTheater', pattern: /^'(?<name>.+?)' is not available at this theater\.$/ },
  { key: 'ticketNotFound', exact: 'Ticket not found.' },
  { key: 'ticketNotPaid', exact: 'Ticket has not been paid.' },
  { key: 'ticketUsed', exact: 'Ticket has already been used.' },
  { key: 'discountInvalid', exact: 'Discount code is invalid or no longer available.' },
  { key: 'invoiceCodeOrPhone', exact: 'An invoice code or a phone number is required.' },
  { key: 'noteRequiredOther', exact: 'A note is required when the reason is Other.' },
  { key: 'refundTenderLimit', exact: 'A refund can be paid back by Cash, Card or QrWallet.' },
  { key: 'refundReferenceRequired', pattern: /^A reference is required for a (?<tender>.+?) refund\.$/ },
  { key: 'openDrawerForRefund', exact: 'Open a cash drawer before paying a refund in cash.' },
  { key: 'drawerShortForRefund', exact: 'The drawer does not hold enough cash for this refund.' },
  { key: 'invoiceAlreadyRefunded', exact: 'This invoice has already been refunded.' },
  { key: 'differenceTenderLimit', exact: 'A price difference can be paid back by Cash, Card or QrWallet.' },
  { key: 'onlyCounterExchange', exact: 'Only a counter sale can be exchanged at the counter; refund an online booking instead.' },
  { key: 'reprintReasonRequired', exact: 'A reason is required to reprint tickets.' },
  { key: 'onlyPaidReprint', exact: 'Only a paid invoice can be reprinted.' },
  { key: 'drawerNotFound', exact: 'Cash drawer not found.' },
  { key: 'onlyOpenerCloses', exact: 'Only the cashier who opened a drawer can close it.' },
  { key: 'drawerAlreadyClosed', exact: 'This drawer is already closed.' },
  { key: 'countedCashNegative', exact: 'The counted cash cannot be negative.' },
  { key: 'cashierMustClose', exact: 'The cashier must close this drawer first.' },
  { key: 'drawerAlreadyReconciled', exact: 'This drawer is already reconciled.' },
  { key: 'invoiceNotFound', exact: 'Invoice not found.' },
  { key: 'onlyPaidRefundExchange', exact: 'Only a paid invoice can be refunded or exchanged.' },
  { key: 'ticketAlreadyUsed', exact: 'A ticket of this invoice has already been used.' },
  { key: 'saleNeedsItem', exact: 'A sale must include at least one seat or food item.' },
  { key: 'seatListedOnce', exact: 'Each seat can be listed only once.' },
  { key: 'foodListedOnce', exact: 'Each food item can be listed only once; use its quantity.' },
  { key: 'attachMemberForPoints', exact: 'Attach a member to redeem points.' },
  { key: 'customerNotFound', exact: 'The selected customer was not found.' },
  { key: 'terminalRequired', exact: 'A terminal name is required.' },
  { key: 'floatNegative', exact: 'The opening float cannot be negative.' },
  { key: 'alreadyOpenDrawer', exact: 'You already have an open cash drawer.' },
  { key: 'terminalHasOpenDrawer', exact: 'This terminal already has an open cash drawer.' },
  { key: 'payInOutOnly', exact: 'Only a pay-in or a pay-out can be recorded here.' },
  { key: 'amountPositive', exact: 'The amount must be greater than zero.' },
  { key: 'noteRequired', exact: 'A note is required.' },
  { key: 'openDrawerFirst', exact: 'Open a cash drawer first.' },
  { key: 'drawerShort', exact: 'The drawer does not hold that much cash.' },
  { key: 'noCustomerForPhone', exact: 'No customer with that phone number.' },
  { key: 'templateNeedsName', exact: 'The template needs a name.' },
  { key: 'templateItemCount', pattern: /^A template needs between 1 and (?<max>.+?) items\.$/ },
  { key: 'itemNeedsText', exact: 'Every checklist item needs a text.' },
  { key: 'templateNotFound', exact: 'Checklist template not found.' },
  { key: 'activeChecklistExists', exact: 'The theater already has an active checklist of this kind. Deactivate it first.' },
  { key: 'showTimeNotInRoom', exact: 'Showtime not found in that room.' },
  { key: 'showTimeOtherTheaterShort', exact: 'The showtime belongs to another theater.' },
  { key: 'noActiveChecklist', exact: 'This theater has no active checklist of that kind.' },
  { key: 'checklistItemNotFound', exact: 'Checklist item not found.' },
  { key: 'checklistCompleted', exact: 'The checklist is already completed.' },
  { key: 'checklistNotFound', exact: 'Checklist not found.' },
  { key: 'requiredItemsPending', pattern: /^(?<missing>.+?) required item\(s\) are not done yet\.$/ },
  { key: 'checklistOutOfScope', exact: 'The checklist is outside your scope.' },
  { key: 'checklistOtherTheater', exact: 'The checklist belongs to another theater.' },
  { key: 'comboNeedsComponent', exact: 'A combo needs at least one component.' },
  { key: 'componentOnce', exact: 'A component can only appear once in a combo.' },
  { key: 'comboSelfContained', exact: 'A combo cannot contain itself.' },
  { key: 'comboNoStock', exact: 'A combo holds no stock: turn off inventory tracking on it first.' },
  { key: 'itemInCombos', pattern: /^This item is a component of combo\(s\): (?<combos>.+?)\. Combos cannot be nested\.$/ },
  { key: 'componentOtherTheater', pattern: /^Component '(?<name>.+?)' belongs to a different theater than the combo\.$/ },
  { key: 'componentIsCombo', pattern: /^Component '(?<name>.+?)' is itself a combo; combos cannot be nested\.$/ },
  { key: 'foodOrderNotFound', exact: 'Food order not found.' },
  { key: 'onlyPaidFoodOrder', exact: 'Only a paid order can be prepared or handed over.' },
  { key: 'foodOrderTransition', pattern: /^A food order cannot move from (?<from>.+?) to (?<to>.+?)\.$/ },
  { key: 'foodOrderConflict', exact: 'The food order was just updated by someone else. Refresh and try again.' },
  { key: 'invoiceCodeRequired', exact: 'An invoice code is required.' },
  { key: 'noFoodOrderForCode', exact: 'No food order found for this code.' },
  { key: 'contactOrInvoiceRequired', exact: 'An email, a phone number or an invoice code is required.' },
  { key: 'invoiceOtherTheater', exact: 'The invoice belongs to another theater.' },
  { key: 'onlyPaidResend', exact: 'Only a paid invoice has an e-ticket to resend.' },
  { key: 'resendLimit', pattern: /^The e-ticket was already resent (?<limit>.+?) times in the last hour\. Try again later\.$/ },
  { key: 'descriptionRequired', exact: 'A description is required.' },
  { key: 'complaintNotFound', exact: 'Complaint not found.' },
  { key: 'onlyOpenComplaintReview', exact: 'Only an open complaint can be taken into review.' },
  { key: 'assigneeNotFound', exact: 'The assignee was not found.' },
  { key: 'rejectReasonRequired', exact: 'A reason is required to reject a complaint.' },
  { key: 'refundNeedsInvoice', exact: 'A refund needs the complaint to be linked to an invoice.' },
  { key: 'pointsWhole', exact: 'Points must be a whole number.' },
  { key: 'chooseResolution', exact: 'Choose a resolution: Refund, GiftCard, Points or Apology.' },
  { key: 'customerNoEmail', exact: 'The customer has no email to issue the gift card to.' },
  { key: 'positiveAmountRequired', pattern: /^A positive (?<what>.+?) amount is required\.$/ },
  { key: 'resolutionNeedsCustomer', exact: 'This resolution needs the complaint to be linked to a customer account.' },
  { key: 'customerAccountNotFound', exact: 'The customer account was not found.' },
  { key: 'complaintOutOfScope', exact: 'The complaint is outside your scope.' },
  { key: 'complaintClosed', exact: 'The complaint is already closed.' },
  { key: 'invoiceNoContact', exact: 'The invoice has no customer contact: an address is required.' },
  { key: 'invalidEmail', exact: 'The address is not a valid email.' },
  { key: 'usedInCombos', pattern: /^Used in combo\(s\): (?<combos>.+?)$/ },
  { key: 'comboCannotMove', exact: 'A combo cannot be moved to another theater.' },
  { key: 'cannotChangeTheaterCombos', pattern: /^Cannot change theater: used in combo\(s\): (?<combos>.+?)$/ },
  { key: 'cannotChangeTheaterStock', exact: 'Cannot change theater: the item has inventory or stock history.' },
  { key: 'giftCardAmountPositive', exact: 'Gift card amount must be positive.' },
  { key: 'seatNotInGivenRoom', exact: 'The seat does not belong to the given room.' },
  { key: 'incidentNotFound', exact: 'Incident not found.' },
  { key: 'incidentResolved', exact: 'The incident is already resolved.' },
  { key: 'seatAlreadyBlocked', exact: 'The seat is already blocked.' },
  { key: 'onlyOpenRoomBlock', exact: 'Only a room that is open for sale can be blocked.' },
  { key: 'incidentOutOfScope', exact: 'The incident is outside your scope.' },
  { key: 'seatNotFoundShort', exact: 'Seat not found.' },
  { key: 'roomNotFoundShort', exact: 'Room not found.' },
  { key: 'roomOtherTheater', exact: 'The room belongs to another theater.' },
  { key: 'incidentOtherTheater', exact: 'The incident belongs to another theater.' },
  { key: 'comboNoOwnStock', exact: 'A combo holds no stock of its own; track its component items instead.' },
  { key: 'openingQtyRequired', exact: 'An opening quantity is required when inventory tracking is turned on.' },
  { key: 'manualMovementKinds', exact: 'Only Adjust and Waste movements can be recorded manually.' },
  { key: 'openingBalanceReserved', exact: 'The OpeningBalance reason is reserved for the system.' },
  { key: 'wasteQtyPositive', exact: 'A waste quantity must be greater than zero.' },
  { key: 'adjustmentNotZero', exact: 'An adjustment cannot be zero.' },
  { key: 'negativeStock', exact: 'Stock cannot go below zero.' },
  { key: 'comboOwnStockTracked', exact: 'A combo holds no stock of its own; its component items are tracked instead.' },
  { key: 'trackingNotEnabled', exact: 'Inventory tracking is not enabled for this item.' },
  { key: 'approvalRequired', exact: 'Manager approval is required for this action.' },
  { key: 'approvalRefused', exact: 'Manager approval was refused.' },
  { key: 'pinLength', pattern: /^The PIN must be (?<min>.+?) to (?<max>.+?) digits\.$/ },
  { key: 'movieTypePairingExists', exact: 'This movie / movie-type pairing already exists.' },
  { key: 'seatKindOtherTheater', exact: 'The seat kind does not belong to this theater.' },
  { key: 'patronNameExists', exact: 'A category with this name already exists for this seat kind.' },
  { key: 'turnoverBufferRange', pattern: /^TurnoverBufferMinutes must be between 0 and (?<max>.+?) minutes\.$/ },
  { key: 'patronOtherTheater', exact: 'One or more patron categories do not belong to this room type\'s theater.' },
  { key: 'priceNegative', exact: 'Price must not be negative.' },
  { key: 'priceMultiplierPositive', exact: 'PriceMultiplier must be greater than 0.' },
  { key: 'roomTurnover', pattern: /^This room needs (?<minutes>.+?) minutes of turnover time between screenings; that slot is too close to an existing showtime\.$/ },
  { key: 'roomOverlap', exact: 'This room already has a showtime overlapping that time window.' },
  { key: 'showTimeEndAfterStart', exact: 'A showtime must end after it starts.' },
  { key: 'showTimePast', exact: 'A showtime cannot be scheduled in the past.' },
  { key: 'movieRuntime', pattern: /^'(?<title>.+?)' runs (?<duration>.+?) minutes; the showtime must end no earlier than (?<end>.+?)\.$/ },
  { key: 'movieNotShowing', pattern: /^'(?<title>.+?)' is no longer showing; reactivate the movie before scheduling it\.$/ },
  { key: 'movieNotReleased', pattern: /^'(?<title>.+?)' is not released until (?<date>.+?); the showtime cannot start before then\.$/ },
  { key: 'movieRunFinished', pattern: /^'(?<title>.+?)' finished its run on (?<date>.+?); the showtime cannot start after then\.$/ },
  { key: 'theaterClosed', pattern: /^Theater '(?<theater>.+?)' is closed; pick a room in an active theater\.$/ },
  { key: 'roomMaintenance', exact: 'That room is under maintenance and cannot host a showtime; pick another room.' },
  { key: 'roomNotInService', exact: 'That room is not in service; pick another room.' },
  { key: 'room3dUnsupported', pattern: /^Room class '(?<room>.+?)' cannot screen 3D\. Pick a 3D-capable room or set the showtime to 2D\.$/ },
  { key: 'theaterOutOfScope', exact: 'The requested theater is outside your scope.' },
  { key: 'dateRangeRequired', exact: 'A date range is required.' },
  { key: 'endBeforeStart', exact: 'The end date must not be before the start date.' },
  { key: 'reportRangeLimit', pattern: /^The report range is limited to (?<days>.+?) days\.$/ },
  { key: 'planIdRequired', exact: 'The plan id is required.' },
  { key: 'planTheaterLocked', exact: 'The theater of a plan cannot be changed.' },
  { key: 'planNeedsItemSubmit', exact: 'A plan needs at least one item before it can be submitted.' },
  { key: 'planRejectReason', exact: 'A reason is required to reject a plan.' },
  { key: 'receivedQtyNegative', exact: 'A received quantity cannot be negative.' },
  { key: 'itemNotInPlan', pattern: /^Item (?<item>.+?) is not part of plan (?<plan>.+?)\.$/ },
  { key: 'trackingDisabledFor', pattern: /^Inventory tracking is no longer enabled for '(?<name>.+?)'\.$/ },
  { key: 'stockUpdateFailed', exact: 'Stock could not be updated.' },
  { key: 'noLowStockItems', exact: 'No low-stock items with a target level.' },
  { key: 'planModified', exact: 'The plan was modified by someone else, please reload.' },
  { key: 'targetDatePast', exact: 'The target date cannot be in the past.' },
  { key: 'supplierTooLong', exact: 'The supplier is too long (max 200 characters).' },
  { key: 'noteTooLong', exact: 'The note is too long (max 1000 characters).' },
  { key: 'planNeedsItem', exact: 'A plan needs at least one item.' },
  { key: 'itemTwiceInPlan', exact: 'The same item cannot appear twice in a plan.' },
  { key: 'plannedQtyRange', pattern: /^A planned quantity must be between 1 and (?<max>.+?)\.$/ },
  { key: 'unitCostNegative', exact: 'A unit cost cannot be negative.' },
  { key: 'itemOtherTheater', pattern: /^Item (?<item>.+?) does not belong to this theater\.$/ },
  { key: 'planItemIsCombo', pattern: /^'(?<name>.+?)' is a combo; plan its component items instead\.$/ },
  { key: 'trackingNotEnabledFor', pattern: /^Inventory tracking is not enabled for '(?<name>.+?)'\.$/ },
  { key: 'planCodeCollision', exact: 'Could not generate a unique plan code, please try again.' },
  { key: 'tenderPositive', exact: 'Every tender must be greater than zero.' },
  { key: 'paymentReferenceRequired', pattern: /^A reference is required for a (?<method>.+?) payment\.$/ },
  { key: 'paymentReferenceTooLong', exact: 'The payment reference is too long.' },
  { key: 'tenderMethods', exact: 'Only Cash, Card and QrWallet can be tendered; use points or a gift card code to apply those.' },
  { key: 'tenderExceedsDue', exact: 'Card and QR payments exceed the amount due.' },
  { key: 'paymentShort', pattern: /^The payment is short by (?<amount>.+?) VND\.$/ },
  { key: 'noCashDue', exact: 'No cash is due for this sale.' },
  { key: 'shiftEndAfterStart', exact: 'The shift must end after it starts.' },
  { key: 'shiftTooLong', pattern: /^A shift can last at most (?<hours>.+?) hours\.$/ },
  { key: 'shiftNotFound', exact: 'Shift not found.' },
  { key: 'shiftOtherTheater', exact: 'The shift belongs to another theater.' },
  { key: 'shiftOverlap', exact: 'This person already has a shift that overlaps these hours.' },
  { key: 'alreadyClockedIn', exact: 'You are already clocked in.' },
  { key: 'notClockedIn', exact: 'You are not clocked in.' },
  { key: 'taskNotFound', exact: 'Task not found.' },
  { key: 'taskOtherTheater', exact: 'The task belongs to another theater.' },
  { key: 'taskAssignedToOther', exact: 'This task is assigned to someone else.' },
  { key: 'taskCancelled', exact: 'The task was cancelled.' },
  { key: 'onlyManagerCancelTask', exact: 'Only a manager can cancel a task.' },
  { key: 'rangeEndAfterStart', exact: 'The end of the range must be after its start.' },
  { key: 'rangeSpan', pattern: /^The range can span at most (?<days>.+?) days\.$/ },
  { key: 'recordOutOfScope', exact: 'The record is outside your scope.' },
  { key: 'staffNotFound', exact: 'Staff member not found.' },
  { key: 'notActiveStaff', exact: 'That person is not an active staff member of this theater.' },
];

const EXACT = new Map<string, string>();
const PATTERNS: { key: string; pattern: RegExp }[] = [];
for (const rule of API_ERROR_RULES) {
  if (rule.exact !== undefined) {
    EXACT.set(rule.exact, rule.key);
  } else if (rule.pattern) {
    PATTERNS.push({ key: rule.key, pattern: rule.pattern });
  }
}

export interface ApiErrorMatch {
  key: string;
  params: Record<string, string>;
}

/** Finds the rule for a server message, or null when the message is not in the catalog. */
export function matchApiError(message: string): ApiErrorMatch | null {
  const text = message.trim();
  const exactKey = EXACT.get(text);
  if (exactKey) {
    return { key: exactKey, params: {} };
  }
  for (const { key, pattern } of PATTERNS) {
    const found = pattern.exec(text);
    if (found) {
      return { key, params: { ...found.groups } };
    }
  }
  return null;
}
