/* spellcheck: off */

//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';

export class PaymentServiceAgent { }
export namespace PaymentServiceAgent {
export const PAYMENT_BASE_URL = new InjectionToken<string>('PAYMENT_BASE_URL');

export interface IHttpService {
    getSeats(search: PagingSearchDTO): Observable<DefaultSearchResultsOfSeatDTO>;
    createBooking(request: CreateBookingRequest): Observable<BookingResultDTO>;
    confirmPayment(request: ConfirmPaymentRequest): Observable<void>;
    cancelBooking(request: CancelBookingRequest): Observable<void>;
    getMyInvoices(search: PagingSearchDTO): Observable<DefaultSearchResultsOfInvoiceDTO>;
    getInvoice(id?: string | undefined): Observable<InvoiceDTO>;
    getInvoices(search: PagingSearchDTO): Observable<DefaultSearchResultsOfInvoiceDTO>;
    getRevenue(from?: Date | undefined, to?: Date | undefined): Observable<any>;
}

@Injectable()
export class HttpService implements IHttpService {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(PAYMENT_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ?? "localhost:5102";
    }

    getSeats(search: PagingSearchDTO): Observable<DefaultSearchResultsOfSeatDTO> {
        let url_ = this.baseUrl + "/api/Payment/GetSeats";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(search);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetSeats(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetSeats(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<DefaultSearchResultsOfSeatDTO>;
                }
            } else
                return _observableThrow(response_) as any as Observable<DefaultSearchResultsOfSeatDTO>;
        }));
    }

    protected processGetSeats(response: HttpResponseBase): Observable<DefaultSearchResultsOfSeatDTO> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = DefaultSearchResultsOfSeatDTO.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    createBooking(request: CreateBookingRequest): Observable<BookingResultDTO> {
        let url_ = this.baseUrl + "/api/Payment/CreateBooking";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processCreateBooking(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processCreateBooking(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<BookingResultDTO>;
                }
            } else
                return _observableThrow(response_) as any as Observable<BookingResultDTO>;
        }));
    }

    protected processCreateBooking(response: HttpResponseBase): Observable<BookingResultDTO> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = BookingResultDTO.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    confirmPayment(request: ConfirmPaymentRequest): Observable<void> {
        let url_ = this.baseUrl + "/api/Payment/ConfirmPayment";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processConfirmPayment(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processConfirmPayment(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<void>;
                }
            } else
                return _observableThrow(response_) as any as Observable<void>;
        }));
    }

    protected processConfirmPayment(response: HttpResponseBase): Observable<void> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return _observableOf(null as any);
            }));
        } else if (status === 400) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = ProblemDetails.fromJS(resultData400);
            return throwException("A server side error occurred.", status, _responseText, _headers, result400);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    cancelBooking(request: CancelBookingRequest): Observable<void> {
        let url_ = this.baseUrl + "/api/Payment/CancelBooking";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processCancelBooking(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processCancelBooking(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<void>;
                }
            } else
                return _observableThrow(response_) as any as Observable<void>;
        }));
    }

    protected processCancelBooking(response: HttpResponseBase): Observable<void> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return _observableOf(null as any);
            }));
        } else if (status === 400) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = ProblemDetails.fromJS(resultData400);
            return throwException("A server side error occurred.", status, _responseText, _headers, result400);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    getMyInvoices(search: PagingSearchDTO): Observable<DefaultSearchResultsOfInvoiceDTO> {
        let url_ = this.baseUrl + "/api/Payment/GetMyInvoices";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(search);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetMyInvoices(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetMyInvoices(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<DefaultSearchResultsOfInvoiceDTO>;
                }
            } else
                return _observableThrow(response_) as any as Observable<DefaultSearchResultsOfInvoiceDTO>;
        }));
    }

    protected processGetMyInvoices(response: HttpResponseBase): Observable<DefaultSearchResultsOfInvoiceDTO> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = DefaultSearchResultsOfInvoiceDTO.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    getInvoice(id?: string | undefined): Observable<InvoiceDTO> {
        let url_ = this.baseUrl + "/api/Payment/GetInvoice?";
        if (id === null)
            throw new Error("The parameter 'id' cannot be null.");
        else if (id !== undefined)
            url_ += "id=" + encodeURIComponent("" + id) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetInvoice(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetInvoice(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<InvoiceDTO>;
                }
            } else
                return _observableThrow(response_) as any as Observable<InvoiceDTO>;
        }));
    }

    protected processGetInvoice(response: HttpResponseBase): Observable<InvoiceDTO> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = InvoiceDTO.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    getInvoices(search: PagingSearchDTO): Observable<DefaultSearchResultsOfInvoiceDTO> {
        let url_ = this.baseUrl + "/api/Payment/GetInvoices";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(search);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetInvoices(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetInvoices(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<DefaultSearchResultsOfInvoiceDTO>;
                }
            } else
                return _observableThrow(response_) as any as Observable<DefaultSearchResultsOfInvoiceDTO>;
        }));
    }

    protected processGetInvoices(response: HttpResponseBase): Observable<DefaultSearchResultsOfInvoiceDTO> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = DefaultSearchResultsOfInvoiceDTO.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    getRevenue(from?: Date | undefined, to?: Date | undefined): Observable<any> {
        let url_ = this.baseUrl + "/api/Payment/GetRevenue?";
        if (from === null)
            throw new Error("The parameter 'from' cannot be null.");
        else if (from !== undefined)
            url_ += "from=" + encodeURIComponent(from ? "" + from.toISOString() : "") + "&";
        if (to === null)
            throw new Error("The parameter 'to' cannot be null.");
        else if (to !== undefined)
            url_ += "to=" + encodeURIComponent(to ? "" + to.toISOString() : "") + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetRevenue(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetRevenue(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<any>;
                }
            } else
                return _observableThrow(response_) as any as Observable<any>;
        }));
    }

    protected processGetRevenue(response: HttpResponseBase): Observable<any> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = resultData200 !== undefined ? resultData200 : <any>null;
    
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

export abstract class BaseSearchResultsOfSeatDTO implements IBaseSearchResultsOfSeatDTO {
    results?: SeatDTO[];
    totalCount?: number;
    countPerPage?: number;
    page?: number;

    constructor(data?: IBaseSearchResultsOfSeatDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["results"])) {
                this.results = [] as any;
                for (let item of _data["results"])
                    this.results!.push(SeatDTO.fromJS(item));
            }
            this.totalCount = _data["totalCount"];
            this.countPerPage = _data["countPerPage"];
            this.page = _data["page"];
        }
    }

    static fromJS(data: any): BaseSearchResultsOfSeatDTO {
        data = typeof data === 'object' ? data : {};
        throw new Error("The abstract class 'BaseSearchResultsOfSeatDTO' cannot be instantiated.");
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.results)) {
            data["results"] = [];
            for (let item of this.results)
                data["results"].push(item.toJSON());
        }
        data["totalCount"] = this.totalCount;
        data["countPerPage"] = this.countPerPage;
        data["page"] = this.page;
        return data;
    }
}

export interface IBaseSearchResultsOfSeatDTO {
    results?: SeatDTO[];
    totalCount?: number;
    countPerPage?: number;
    page?: number;
}

export class DefaultSearchResultsOfSeatDTO extends BaseSearchResultsOfSeatDTO implements IDefaultSearchResultsOfSeatDTO {

    constructor(data?: IDefaultSearchResultsOfSeatDTO) {
        super(data);
    }

    override init(_data?: any) {
        super.init(_data);
    }

    static override fromJS(data: any): DefaultSearchResultsOfSeatDTO {
        data = typeof data === 'object' ? data : {};
        let result = new DefaultSearchResultsOfSeatDTO();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        super.toJSON(data);
        return data;
    }
}

export interface IDefaultSearchResultsOfSeatDTO extends IBaseSearchResultsOfSeatDTO {
}

export class SeatDTO implements ISeatDTO {
    id?: string;
    rowName?: string;
    colIndex?: number;
    seatTypeId?: string;
    seatTypeName?: string;
    seatTypeColor?: string;
    status?: SeatStatus;
    price?: number;
    isLocked?: boolean;

    constructor(data?: ISeatDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.rowName = _data["rowName"];
            this.colIndex = _data["colIndex"];
            this.seatTypeId = _data["seatTypeId"];
            this.seatTypeName = _data["seatTypeName"];
            this.seatTypeColor = _data["seatTypeColor"];
            this.status = _data["status"];
            this.price = _data["price"];
            this.isLocked = _data["isLocked"];
        }
    }

    static fromJS(data: any): SeatDTO {
        data = typeof data === 'object' ? data : {};
        let result = new SeatDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["rowName"] = this.rowName;
        data["colIndex"] = this.colIndex;
        data["seatTypeId"] = this.seatTypeId;
        data["seatTypeName"] = this.seatTypeName;
        data["seatTypeColor"] = this.seatTypeColor;
        data["status"] = this.status;
        data["price"] = this.price;
        data["isLocked"] = this.isLocked;
        return data;
    }
}

export interface ISeatDTO {
    id?: string;
    rowName?: string;
    colIndex?: number;
    seatTypeId?: string;
    seatTypeName?: string;
    seatTypeColor?: string;
    status?: SeatStatus;
    price?: number;
    isLocked?: boolean;
}

export enum SeatStatus {
    Available = 0,
    Reserved = 1,
    Occupied = 2,
}

export class PagingSearchDTO implements IPagingSearchDTO {
    pageIndex?: number;
    pageSize?: number;
    filters?: { [key: string]: string; } | undefined;
    sort?: SortDTO | undefined;

    constructor(data?: IPagingSearchDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.pageIndex = _data["pageIndex"];
            this.pageSize = _data["pageSize"];
            if (_data["filters"]) {
                this.filters = {} as any;
                for (let key in _data["filters"]) {
                    if (_data["filters"].hasOwnProperty(key))
                        (<any>this.filters)![key] = _data["filters"][key];
                }
            }
            this.sort = _data["sort"] ? SortDTO.fromJS(_data["sort"]) : <any>undefined;
        }
    }

    static fromJS(data: any): PagingSearchDTO {
        data = typeof data === 'object' ? data : {};
        let result = new PagingSearchDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["pageIndex"] = this.pageIndex;
        data["pageSize"] = this.pageSize;
        if (this.filters) {
            data["filters"] = {};
            for (let key in this.filters) {
                if (this.filters.hasOwnProperty(key))
                    (<any>data["filters"])[key] = (<any>this.filters)[key];
            }
        }
        data["sort"] = this.sort ? this.sort.toJSON() : <any>undefined;
        return data;
    }
}

export interface IPagingSearchDTO {
    pageIndex?: number;
    pageSize?: number;
    filters?: { [key: string]: string; } | undefined;
    sort?: SortDTO | undefined;
}

export class SortDTO implements ISortDTO {
    field?: string;
    ascending?: boolean;

    constructor(data?: ISortDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.field = _data["field"];
            this.ascending = _data["ascending"];
        }
    }

    static fromJS(data: any): SortDTO {
        data = typeof data === 'object' ? data : {};
        let result = new SortDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["field"] = this.field;
        data["ascending"] = this.ascending;
        return data;
    }
}

export interface ISortDTO {
    field?: string;
    ascending?: boolean;
}

export class BookingResultDTO implements IBookingResultDTO {
    invoiceId?: string;
    invoiceCode?: string;
    totalAmount?: number;
    discountAmount?: number;
    finalAmount?: number;
    status?: InvoiceStatus;
    paymentUrl?: string | undefined;
    tickets?: TicketItemDTO[];

    constructor(data?: IBookingResultDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.invoiceId = _data["invoiceId"];
            this.invoiceCode = _data["invoiceCode"];
            this.totalAmount = _data["totalAmount"];
            this.discountAmount = _data["discountAmount"];
            this.finalAmount = _data["finalAmount"];
            this.status = _data["status"];
            this.paymentUrl = _data["paymentUrl"];
            if (Array.isArray(_data["tickets"])) {
                this.tickets = [] as any;
                for (let item of _data["tickets"])
                    this.tickets!.push(TicketItemDTO.fromJS(item));
            }
        }
    }

    static fromJS(data: any): BookingResultDTO {
        data = typeof data === 'object' ? data : {};
        let result = new BookingResultDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["invoiceId"] = this.invoiceId;
        data["invoiceCode"] = this.invoiceCode;
        data["totalAmount"] = this.totalAmount;
        data["discountAmount"] = this.discountAmount;
        data["finalAmount"] = this.finalAmount;
        data["status"] = this.status;
        data["paymentUrl"] = this.paymentUrl;
        if (Array.isArray(this.tickets)) {
            data["tickets"] = [];
            for (let item of this.tickets)
                data["tickets"].push(item.toJSON());
        }
        return data;
    }
}

export interface IBookingResultDTO {
    invoiceId?: string;
    invoiceCode?: string;
    totalAmount?: number;
    discountAmount?: number;
    finalAmount?: number;
    status?: InvoiceStatus;
    paymentUrl?: string | undefined;
    tickets?: TicketItemDTO[];
}

export enum InvoiceStatus {
    Pending = 0,
    Paid = 1,
    Cancelled = 2,
    Failed = 3,
}

export class TicketItemDTO implements ITicketItemDTO {
    seatLabel?: string;
    seatType?: string;
    ticketType?: string;
    price?: number;
    qrCode?: string | undefined;

    constructor(data?: ITicketItemDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.seatLabel = _data["seatLabel"];
            this.seatType = _data["seatType"];
            this.ticketType = _data["ticketType"];
            this.price = _data["price"];
            this.qrCode = _data["qrCode"];
        }
    }

    static fromJS(data: any): TicketItemDTO {
        data = typeof data === 'object' ? data : {};
        let result = new TicketItemDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["seatLabel"] = this.seatLabel;
        data["seatType"] = this.seatType;
        data["ticketType"] = this.ticketType;
        data["price"] = this.price;
        data["qrCode"] = this.qrCode;
        return data;
    }
}

export interface ITicketItemDTO {
    seatLabel?: string;
    seatType?: string;
    ticketType?: string;
    price?: number;
    qrCode?: string | undefined;
}

export class CreateBookingRequest implements ICreateBookingRequest {
    showTimeId?: string;
    roomId?: string;
    seats?: BookingSeatItem[];
    foods?: BookingFoodItem[];
    discountCode?: string | undefined;
    paymentMethod?: string;

    constructor(data?: ICreateBookingRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.showTimeId = _data["showTimeId"];
            this.roomId = _data["roomId"];
            if (Array.isArray(_data["seats"])) {
                this.seats = [] as any;
                for (let item of _data["seats"])
                    this.seats!.push(BookingSeatItem.fromJS(item));
            }
            if (Array.isArray(_data["foods"])) {
                this.foods = [] as any;
                for (let item of _data["foods"])
                    this.foods!.push(BookingFoodItem.fromJS(item));
            }
            this.discountCode = _data["discountCode"];
            this.paymentMethod = _data["paymentMethod"];
        }
    }

    static fromJS(data: any): CreateBookingRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CreateBookingRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["showTimeId"] = this.showTimeId;
        data["roomId"] = this.roomId;
        if (Array.isArray(this.seats)) {
            data["seats"] = [];
            for (let item of this.seats)
                data["seats"].push(item.toJSON());
        }
        if (Array.isArray(this.foods)) {
            data["foods"] = [];
            for (let item of this.foods)
                data["foods"].push(item.toJSON());
        }
        data["discountCode"] = this.discountCode;
        data["paymentMethod"] = this.paymentMethod;
        return data;
    }
}

export interface ICreateBookingRequest {
    showTimeId?: string;
    roomId?: string;
    seats?: BookingSeatItem[];
    foods?: BookingFoodItem[];
    discountCode?: string | undefined;
    paymentMethod?: string;
}

export class BookingSeatItem implements IBookingSeatItem {
    seatId?: string;
    ticketTypeId?: string;

    constructor(data?: IBookingSeatItem) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.seatId = _data["seatId"];
            this.ticketTypeId = _data["ticketTypeId"];
        }
    }

    static fromJS(data: any): BookingSeatItem {
        data = typeof data === 'object' ? data : {};
        let result = new BookingSeatItem();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["seatId"] = this.seatId;
        data["ticketTypeId"] = this.ticketTypeId;
        return data;
    }
}

export interface IBookingSeatItem {
    seatId?: string;
    ticketTypeId?: string;
}

export class BookingFoodItem implements IBookingFoodItem {
    foodAndDrinkId?: string;
    quantity?: number;

    constructor(data?: IBookingFoodItem) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.foodAndDrinkId = _data["foodAndDrinkId"];
            this.quantity = _data["quantity"];
        }
    }

    static fromJS(data: any): BookingFoodItem {
        data = typeof data === 'object' ? data : {};
        let result = new BookingFoodItem();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["foodAndDrinkId"] = this.foodAndDrinkId;
        data["quantity"] = this.quantity;
        return data;
    }
}

export interface IBookingFoodItem {
    foodAndDrinkId?: string;
    quantity?: number;
}

export class ProblemDetails implements IProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;

    [key: string]: any;

    constructor(data?: IProblemDetails) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.type = _data["type"];
            this.title = _data["title"];
            this.status = _data["status"];
            this.detail = _data["detail"];
            this.instance = _data["instance"];
        }
    }

    static fromJS(data: any): ProblemDetails {
        data = typeof data === 'object' ? data : {};
        let result = new ProblemDetails();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["type"] = this.type;
        data["title"] = this.title;
        data["status"] = this.status;
        data["detail"] = this.detail;
        data["instance"] = this.instance;
        return data;
    }
}

export interface IProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;

    [key: string]: any;
}

export class ConfirmPaymentRequest implements IConfirmPaymentRequest {
    invoiceId?: string;
    paymentReference?: string;

    constructor(data?: IConfirmPaymentRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.invoiceId = _data["invoiceId"];
            this.paymentReference = _data["paymentReference"];
        }
    }

    static fromJS(data: any): ConfirmPaymentRequest {
        data = typeof data === 'object' ? data : {};
        let result = new ConfirmPaymentRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["invoiceId"] = this.invoiceId;
        data["paymentReference"] = this.paymentReference;
        return data;
    }
}

export interface IConfirmPaymentRequest {
    invoiceId?: string;
    paymentReference?: string;
}

export class CancelBookingRequest implements ICancelBookingRequest {
    invoiceId?: string;

    constructor(data?: ICancelBookingRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.invoiceId = _data["invoiceId"];
        }
    }

    static fromJS(data: any): CancelBookingRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CancelBookingRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["invoiceId"] = this.invoiceId;
        return data;
    }
}

export interface ICancelBookingRequest {
    invoiceId?: string;
}

export abstract class BaseSearchResultsOfInvoiceDTO implements IBaseSearchResultsOfInvoiceDTO {
    results?: InvoiceDTO[];
    totalCount?: number;
    countPerPage?: number;
    page?: number;

    constructor(data?: IBaseSearchResultsOfInvoiceDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["results"])) {
                this.results = [] as any;
                for (let item of _data["results"])
                    this.results!.push(InvoiceDTO.fromJS(item));
            }
            this.totalCount = _data["totalCount"];
            this.countPerPage = _data["countPerPage"];
            this.page = _data["page"];
        }
    }

    static fromJS(data: any): BaseSearchResultsOfInvoiceDTO {
        data = typeof data === 'object' ? data : {};
        throw new Error("The abstract class 'BaseSearchResultsOfInvoiceDTO' cannot be instantiated.");
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.results)) {
            data["results"] = [];
            for (let item of this.results)
                data["results"].push(item.toJSON());
        }
        data["totalCount"] = this.totalCount;
        data["countPerPage"] = this.countPerPage;
        data["page"] = this.page;
        return data;
    }
}

export interface IBaseSearchResultsOfInvoiceDTO {
    results?: InvoiceDTO[];
    totalCount?: number;
    countPerPage?: number;
    page?: number;
}

export class DefaultSearchResultsOfInvoiceDTO extends BaseSearchResultsOfInvoiceDTO implements IDefaultSearchResultsOfInvoiceDTO {

    constructor(data?: IDefaultSearchResultsOfInvoiceDTO) {
        super(data);
    }

    override init(_data?: any) {
        super.init(_data);
    }

    static override fromJS(data: any): DefaultSearchResultsOfInvoiceDTO {
        data = typeof data === 'object' ? data : {};
        let result = new DefaultSearchResultsOfInvoiceDTO();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        super.toJSON(data);
        return data;
    }
}

export interface IDefaultSearchResultsOfInvoiceDTO extends IBaseSearchResultsOfInvoiceDTO {
}

export class InvoiceDTO implements IInvoiceDTO {
    id?: string;
    code?: string;
    userName?: string;
    userEmail?: string;
    totalAmount?: number;
    discountAmount?: number;
    finalAmount?: number;
    status?: InvoiceStatus;
    paymentMethod?: string | undefined;
    paidAt?: Date | undefined;
    creationTime?: Date;
    tickets?: InvoiceTicketDTO[];
    foods?: InvoiceFoodDTO[];

    constructor(data?: IInvoiceDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.code = _data["code"];
            this.userName = _data["userName"];
            this.userEmail = _data["userEmail"];
            this.totalAmount = _data["totalAmount"];
            this.discountAmount = _data["discountAmount"];
            this.finalAmount = _data["finalAmount"];
            this.status = _data["status"];
            this.paymentMethod = _data["paymentMethod"];
            this.paidAt = _data["paidAt"] ? new Date(_data["paidAt"].toString()) : <any>undefined;
            this.creationTime = _data["creationTime"] ? new Date(_data["creationTime"].toString()) : <any>undefined;
            if (Array.isArray(_data["tickets"])) {
                this.tickets = [] as any;
                for (let item of _data["tickets"])
                    this.tickets!.push(InvoiceTicketDTO.fromJS(item));
            }
            if (Array.isArray(_data["foods"])) {
                this.foods = [] as any;
                for (let item of _data["foods"])
                    this.foods!.push(InvoiceFoodDTO.fromJS(item));
            }
        }
    }

    static fromJS(data: any): InvoiceDTO {
        data = typeof data === 'object' ? data : {};
        let result = new InvoiceDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["code"] = this.code;
        data["userName"] = this.userName;
        data["userEmail"] = this.userEmail;
        data["totalAmount"] = this.totalAmount;
        data["discountAmount"] = this.discountAmount;
        data["finalAmount"] = this.finalAmount;
        data["status"] = this.status;
        data["paymentMethod"] = this.paymentMethod;
        data["paidAt"] = this.paidAt ? this.paidAt.toISOString() : <any>undefined;
        data["creationTime"] = this.creationTime ? this.creationTime.toISOString() : <any>undefined;
        if (Array.isArray(this.tickets)) {
            data["tickets"] = [];
            for (let item of this.tickets)
                data["tickets"].push(item.toJSON());
        }
        if (Array.isArray(this.foods)) {
            data["foods"] = [];
            for (let item of this.foods)
                data["foods"].push(item.toJSON());
        }
        return data;
    }
}

export interface IInvoiceDTO {
    id?: string;
    code?: string;
    userName?: string;
    userEmail?: string;
    totalAmount?: number;
    discountAmount?: number;
    finalAmount?: number;
    status?: InvoiceStatus;
    paymentMethod?: string | undefined;
    paidAt?: Date | undefined;
    creationTime?: Date;
    tickets?: InvoiceTicketDTO[];
    foods?: InvoiceFoodDTO[];
}

export class InvoiceTicketDTO implements IInvoiceTicketDTO {
    movieTitle?: string;
    theaterName?: string;
    roomName?: string;
    showTime?: Date;
    seatLabel?: string;
    ticketType?: string;
    price?: number;
    qrCode?: string | undefined;
    isUsed?: boolean;

    constructor(data?: IInvoiceTicketDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.movieTitle = _data["movieTitle"];
            this.theaterName = _data["theaterName"];
            this.roomName = _data["roomName"];
            this.showTime = _data["showTime"] ? new Date(_data["showTime"].toString()) : <any>undefined;
            this.seatLabel = _data["seatLabel"];
            this.ticketType = _data["ticketType"];
            this.price = _data["price"];
            this.qrCode = _data["qrCode"];
            this.isUsed = _data["isUsed"];
        }
    }

    static fromJS(data: any): InvoiceTicketDTO {
        data = typeof data === 'object' ? data : {};
        let result = new InvoiceTicketDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["movieTitle"] = this.movieTitle;
        data["theaterName"] = this.theaterName;
        data["roomName"] = this.roomName;
        data["showTime"] = this.showTime ? this.showTime.toISOString() : <any>undefined;
        data["seatLabel"] = this.seatLabel;
        data["ticketType"] = this.ticketType;
        data["price"] = this.price;
        data["qrCode"] = this.qrCode;
        data["isUsed"] = this.isUsed;
        return data;
    }
}

export interface IInvoiceTicketDTO {
    movieTitle?: string;
    theaterName?: string;
    roomName?: string;
    showTime?: Date;
    seatLabel?: string;
    ticketType?: string;
    price?: number;
    qrCode?: string | undefined;
    isUsed?: boolean;
}

export class InvoiceFoodDTO implements IInvoiceFoodDTO {
    foodName?: string;
    quantity?: number;
    unitPrice?: number;
    totalPrice?: number;

    constructor(data?: IInvoiceFoodDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.foodName = _data["foodName"];
            this.quantity = _data["quantity"];
            this.unitPrice = _data["unitPrice"];
            this.totalPrice = _data["totalPrice"];
        }
    }

    static fromJS(data: any): InvoiceFoodDTO {
        data = typeof data === 'object' ? data : {};
        let result = new InvoiceFoodDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["foodName"] = this.foodName;
        data["quantity"] = this.quantity;
        data["unitPrice"] = this.unitPrice;
        data["totalPrice"] = this.totalPrice;
        return data;
    }
}

export interface IInvoiceFoodDTO {
    foodName?: string;
    quantity?: number;
    unitPrice?: number;
    totalPrice?: number;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): Observable<any> {
    return _observableThrow(new ApiException(message, status, response, headers, result));
}

function blobToText(blob: any): Observable<string> {
    return new Observable<string>((observer: any) => {
        if (!blob) {
            observer.next("");
            observer.complete();
        } else {
            let reader = new FileReader();
            reader.onload = event => {
                observer.next((event.target as any).result);
                observer.complete();
            };
            reader.readAsText(blob);
        }
    });
}

}