<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\3-Data\Cinema.Data.Contracts\Cinema.Data.Contracts.csproj" />
    <ProjectReference Include="..\Cinema.Business.DTO\Cinema.Business.DTO.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
